/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM.h"
#include "GPIO_Driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay_5seconds(void)
{
	for(volatile uint32_t i=0; i < 6250000; i++);
}

int main(void)
{

  GPIO_Handle_t GPIO_Handle_RED;
  GPIO_Handle_RED.pGPIOx = GPIOD;
  GPIO_Handle_RED.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
  GPIO_Handle_RED.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_7;
  GPIO_Handle_RED.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
  GPIO_Handle_RED.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
  GPIO_Handle_RED.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;

  GPIO_Handle_t GPIO_Handle_YELLOW;
  GPIO_Handle_YELLOW.pGPIOx = GPIOD;
  GPIO_Handle_YELLOW.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
  GPIO_Handle_YELLOW.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_8;
  GPIO_Handle_YELLOW.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
  GPIO_Handle_YELLOW.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
  GPIO_Handle_YELLOW.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;

  GPIO_Handle_t GPIO_Handle_GREEN;
  GPIO_Handle_GREEN.pGPIOx = GPIOD;
  GPIO_Handle_GREEN.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
  GPIO_Handle_GREEN.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_9;
  GPIO_Handle_GREEN.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
  GPIO_Handle_GREEN.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
  GPIO_Handle_GREEN.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;

  GPIO_Init(&GPIO_Handle_RED);
  GPIO_Init(&GPIO_Handle_YELLOW);
  GPIO_Init(&GPIO_Handle_GREEN);

  for(;;){

    GPIO_WriteToOutputPin(&GPIO_Handle_RED, ENABLE);
    GPIO_WriteToOutputPin(&GPIO_Handle_YELLOW, DISABLE);
    GPIO_WriteToOutputPin(&GPIO_Handle_GREEN, DISABLE);
    
    delay_5seconds();

    GPIO_WriteToOutputPin(&GPIO_Handle_RED, ENABLE);
    GPIO_WriteToOutputPin(&GPIO_Handle_YELLOW, ENABLE);
    GPIO_WriteToOutputPin(&GPIO_Handle_GREEN, DISABLE);

    delay_5seconds();

    GPIO_WriteToOutputPin(&GPIO_Handle_RED, DISABLE);
    GPIO_WriteToOutputPin(&GPIO_Handle_YELLOW, DISABLE);
    GPIO_WriteToOutputPin(&GPIO_Handle_GREEN, ENABLE);

    delay_5seconds();

    GPIO_WriteToOutputPin(&GPIO_Handle_RED, DISABLE);
    GPIO_WriteToOutputPin(&GPIO_Handle_YELLOW, ENABLE);
    GPIO_WriteToOutputPin(&GPIO_Handle_GREEN, DISABLE);

    delay_5seconds();

  }
}
